import turtle
tw=turtle.Screen()

ella=turtle.Turtle()
ella.speed(100)

ella.circle(100)
for i in range(3600):
    ella.forward(1)
    ella.left(1)
ella.left(90)
ella.penup()
ella.forward(100)
ella.pendown()
ella.left(180)
ella.forward(50)
ella.penup()
ella.forward(25)
ella.pendown()
ella.left(90)
for i in range(90):
    ella.forward(1)
    ella.left(1)
ella.penup()
ella.left(180)
ella.pendown()
# for i in range(180):
#     ella.forward(1)
#     ella.right(1)
ella.left(180)
# for i in range(180):
#     ella.forward(1)
#     ella.left(1)
ella.penup()
ella.forward(45)
ella.pendown()
ella.circle(26)
ella.penup()
ella.left(90)
ella.forward(125)
ella.left(90)
ella.pendown()
ella.circle(26)
turtle.mainloop()
